apiVersion: apps/v1
kind: Deployment
metadata:
  name: newapp-green
  labels:
    app: my-app
    env: green
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
      env: green
  template:
    metadata:
      labels:
        app: my-app
        env: green
    spec:
      containers:
      - name: cont-1
        image: gstejadocker/mytetrisgame:v2
        ports:
        - containerPort: 3000
